"use client";

import { FormEvent, useMemo, useState, useEffect } from "react";

export type ScopeArea = "Cybersecurity" | "Automation" | "OR ONE";
export type ScopeItem = {
  id: string;
  area: ScopeArea;
  code: string;
  title: string;
  detail: string;
  commercial?: string;
  /**
   * OR ONE only: the individual capability codes selected within this
   * one aggregate scope entry (see app/lib/or-one-capability-registry.ts).
   * Populated by or-one-client.tsx so the server can resolve real
   * per-capability identities instead of just a count — see
   * app/lib/scope-resolve.ts, which is what actually reads this.
   */
  capabilityCodes?: string[];
};

const key = "oragrol-scope-v2";

export function useScope() {
  const [items, setItems] = useState<ScopeItem[]>([]);
  // Hydrate from localStorage after mount (client-only; SSR/first paint stays
  // empty on purpose to avoid a hydration mismatch).
  useEffect(() => {
    try {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- one-time localStorage hydration on mount, not a reactive sync loop
      setItems(JSON.parse(localStorage.getItem(key) || "[]"));
    } catch {
      /* ignore malformed localStorage content */
    }
  }, []);
  useEffect(() => {
    try {
      localStorage.setItem(key, JSON.stringify(items));
    } catch {
      /* storage may be unavailable (private browsing, quota) — non-fatal */
    }
  }, [items]);
  const has = (id: string) => items.some((x) => x.id === id);
  const toggle = (item: ScopeItem) =>
    setItems((s) => (s.some((x) => x.id === item.id) ? s.filter((x) => x.id !== item.id) : [...s, item]));
  const remove = (id: string) => setItems((s) => s.filter((x) => x.id !== id));
  return { items, setItems, has, toggle, remove };
}

// Required before either action can proceed — name, a syntactically
// valid email, phone, AND company (per My_Scope_Final_Ready_For_Claude.md
// Section 1: "Both actions collect four REQUIRED fields"). This is a UX
// gate only; scope-schema.ts enforces the same four fields server-side,
// which is the actual source of truth.
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function isClientReady(client: { name: string; email: string; phone: string; company: string }) {
  return (
    client.name.trim().length > 0 &&
    emailPattern.test(client.email.trim()) &&
    client.phone.trim().length > 0 &&
    client.company.trim().length > 0
  );
}

type ClientInfo = {
  name: string;
  email: string;
  phone: string;
  company: string;
  timeframe: string; // optional field — never required, per Section 1
  context: string; // optional field — never required
};

// Bumps only if the disclosure text below actually changes; recorded
// server-side per action so a future copy change doesn't retroactively
// misdescribe what an earlier submitter actually saw and agreed to.
const DISCLOSURE_VERSION = "2026-09-09";
const DISCLOSURE_TEXT =
  "Your name, contact details and selected scope will be shared with ORAGROL to prepare your document and, " +
  "if you request a review, to follow up with you. This is not a quotation, contract or confirmation of services.";

type SelectionPayload = { id: string; capabilityCodes?: string[] };
function toSelectionPayload(item: ScopeItem): SelectionPayload {
  return item.capabilityCodes && item.capabilityCodes.length > 0
    ? { id: item.id, capabilityCodes: item.capabilityCodes }
    : { id: item.id };
}

type ScopeApiResponse = { reference: string; actionId: string; downloadToken: string };

async function submitScope(
  intent: "pdf_download" | "review_requested",
  items: ScopeItem[],
  client: ClientInfo,
): Promise<ScopeApiResponse> {
  const requestId = crypto.randomUUID();
  const res = await fetch("/api/scope", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      requestId,
      intent,
      name: client.name.trim(),
      email: client.email.trim(),
      phone: client.phone.trim(),
      company: client.company.trim(),
      timeframe: client.timeframe.trim() || undefined,
      context: client.context.trim() || undefined,
      selections: items.map(toSelectionPayload),
      sourcePath: window.location.pathname,
      disclosureVersion: DISCLOSURE_VERSION,
      acknowledged: true, // this function is only ever called after the checkbox is confirmed checked — see the two handlers below
    }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(body?.error || `Request failed (${res.status}).`);
  }
  return res.json();
}

/**
 * The PDF is generated by an async job (scope-worker.ts's
 * pdf_generation handler), not synchronously in the POST response —
 * poll the protected download endpoint until it's ready. 202 = still
 * generating, 200 = ready, anything else = a real error worth stopping
 * on rather than retrying forever.
 */
async function pollForPdf(downloadToken: string, maxAttempts = 20, intervalMs = 1500): Promise<Blob> {
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const res = await fetch(`/api/scope/download?token=${encodeURIComponent(downloadToken)}`);
    if (res.status === 200) return res.blob();
    if (res.status !== 202) {
      const body = await res.json().catch(() => ({}));
      throw new Error(body?.error || `Download failed (${res.status}).`);
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error("Your PDF is taking longer than expected to prepare. Please try again shortly.");
}

function triggerBrowserDownload(blob: Blob, reference: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `ORAGROL_My_Scope_${reference}.pdf`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

type FlowState =
  | { status: "idle" }
  | { status: "submitting"; intent: "pdf_download" | "review_requested" }
  | { status: "preparing_pdf" }
  | { status: "success"; intent: "pdf_download" | "review_requested"; reference: string; downloadToken: string }
  | { status: "error"; message: string };

export function ScopeTray({
  items,
  remove,
  open,
  setOpen,
  activeArea,
}: {
  items: ScopeItem[];
  remove: (id: string) => void;
  open: boolean;
  setOpen: (v: boolean) => void;
  activeArea: ScopeArea;
}) {
  const [client, setClient] = useState<ClientInfo>({
    name: "",
    email: "",
    phone: "",
    company: "",
    timeframe: "",
    context: "",
  });
  const [acknowledged, setAcknowledged] = useState(false);
  const [flow, setFlow] = useState<FlowState>({ status: "idle" });

  const ready = isClientReady(client);
  const canSubmit = ready && acknowledged && items.length > 0;

  const grouped = useMemo(
    () =>
      (["Cybersecurity", "Automation", "OR ONE"] as ScopeArea[])
        .map((area) => ({ area, items: items.filter((x) => x.area === area) }))
        .filter((x) => x.items.length),
    [items],
  );

  const update = (name: keyof ClientInfo, value: string) => setClient((s) => ({ ...s, [name]: value }));

  const handleDownload = async () => {
    if (!canSubmit) return;
    setFlow({ status: "submitting", intent: "pdf_download" });
    try {
      const { reference, downloadToken } = await submitScope("pdf_download", items, client);
      setFlow({ status: "preparing_pdf" });
      const blob = await pollForPdf(downloadToken);
      triggerBrowserDownload(blob, reference);
      setFlow({ status: "success", intent: "pdf_download", reference, downloadToken });
    } catch (err) {
      setFlow({ status: "error", message: err instanceof Error ? err.message : String(err) });
    }
  };

  const handleReviewSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!canSubmit) return;
    setFlow({ status: "submitting", intent: "review_requested" });
    try {
      const { reference, downloadToken } = await submitScope("review_requested", items, client);
      setFlow({ status: "success", intent: "review_requested", reference, downloadToken });
    } catch (err) {
      setFlow({ status: "error", message: err instanceof Error ? err.message : String(err) });
    }
  };

  // Section 1: "a review after a download creates a distinct review
  // event" — a fresh requestId is generated inside submitScope() on
  // every call, so a review submitted after an earlier download is
  // never mistaken by the server for a retry of that download.
  const handleDownloadCopyAfterReview = async () => {
    if (flow.status !== "success") return;
    try {
      const blob = await pollForPdf(flow.downloadToken);
      triggerBrowserDownload(blob, flow.reference);
    } catch (err) {
      setFlow({ status: "error", message: err instanceof Error ? err.message : String(err) });
    }
  };

  const busy = flow.status === "submitting" || flow.status === "preparing_pdf";

  return (
    <>
      <button className="scope-launcher" onClick={() => setOpen(true)}>
        <span>MY SCOPE</span>
        <b>{String(items.length).padStart(2, "0")}</b>
      </button>
      {open && <div className="scope-scrim" onClick={() => setOpen(false)} />}
      <aside className={open ? "scope-tray open" : "scope-tray"} aria-hidden={!open}>
        <div className="scope-or" aria-hidden="true">
          OR
        </div>
        <header>
          <div>
            <span>ORAGROL / PRIVATE SCOPE</span>
            <strong>{String(items.length).padStart(2, "0")} SELECTED</strong>
          </div>
          <button onClick={() => setOpen(false)} aria-label="Close scope tray">
            ×
          </button>
        </header>
        <div className="scope-rail">
          {(["Cybersecurity", "Automation", "OR ONE"] as ScopeArea[]).map((a, i) => (
            <span className={a === activeArea ? "current" : ""} key={a}>
              {i > 0 && <i />}
              {a.toUpperCase()}
            </span>
          ))}
        </div>
        <div className="scope-body">
          {items.length === 0 ? (
            <div className="scope-empty">
              <span>Begin your scope</span>
              <h3>Choose what your business needs.</h3>
              <p>Your selections stay together across Services, Business Automation and OR ONE.</p>
            </div>
          ) : (
            <>
              <section className="scope-summary">
                <span>PRELIMINARY SCOPE</span>
                <h3>A clearer first conversation.</h3>
                <p>Review your selections, add context, then download a PDF or submit for private review.</p>
              </section>
              {grouped.map((group) => (
                <section className="scope-group" key={group.area}>
                  <h4>{group.area}</h4>
                  {group.items.map((item) => (
                    <article key={item.id}>
                      <span>{item.code}</span>
                      <div>
                        <b>{item.title}</b>
                        <small>{item.commercial || item.detail}</small>
                      </div>
                      <button onClick={() => remove(item.id)} disabled={busy}>
                        Remove
                      </button>
                    </article>
                  ))}
                </section>
              ))}

              {flow.status === "success" ? (
                <div className="scope-confirmation-block">
                  <p className="scope-confirmation">
                    {flow.intent === "pdf_download"
                      ? `Your PDF has been downloaded. Reference: ${flow.reference}.`
                      : `Your private review request has been received. Reference: ${flow.reference}.`}
                  </p>
                  {flow.intent === "review_requested" && (
                    <button type="button" className="scope-download-copy" onClick={handleDownloadCopyAfterReview}>
                      Download a copy of your scope PDF
                    </button>
                  )}
                </div>
              ) : (
                <form onSubmit={handleReviewSubmit}>
                  <label>
                    Priority or context
                    <textarea
                      value={client.context}
                      onChange={(e) => update("context", e.target.value)}
                      placeholder="What should improve first?"
                      disabled={busy}
                    />
                  </label>
                  <div>
                    <label>
                      Name
                      <input required value={client.name} onChange={(e) => update("name", e.target.value)} disabled={busy} />
                    </label>
                    <label>
                      Business email
                      <input
                        required
                        type="email"
                        value={client.email}
                        onChange={(e) => update("email", e.target.value)}
                        disabled={busy}
                      />
                    </label>
                  </div>
                  <label>
                    Phone
                    <input required type="tel" value={client.phone} onChange={(e) => update("phone", e.target.value)} disabled={busy} />
                  </label>
                  <label>
                    Company
                    <input required value={client.company} onChange={(e) => update("company", e.target.value)} disabled={busy} />
                  </label>
                  <label>
                    Target timeframe <small>(optional)</small>
                    <select value={client.timeframe} onChange={(e) => update("timeframe", e.target.value)} disabled={busy}>
                      <option value="">Not specified</option>
                      <option>Within 30 days</option>
                      <option>1-3 months</option>
                      <option>3-6 months</option>
                      <option>Exploring options</option>
                    </select>
                  </label>
                  <p className="scope-disclosure">{DISCLOSURE_TEXT}</p>
                  <label className="scope-consent">
                    <input
                      required
                      type="checkbox"
                      checked={acknowledged}
                      onChange={(e) => setAcknowledged(e.target.checked)}
                      disabled={busy}
                    />{" "}
                    I have read the above and agree that ORAGROL may contact me about this scope.
                  </label>

                  {flow.status === "error" && <p className="scope-error">{flow.message}</p>}

                  <div className="scope-actions">
                    <button className="scope-download" type="button" disabled={!canSubmit || busy} onClick={handleDownload}>
                      {flow.status === "submitting" && flow.intent === "pdf_download"
                        ? "Submitting…"
                        : flow.status === "preparing_pdf"
                          ? "Preparing your PDF…"
                          : "Download My Scope PDF"}
                    </button>
                    <button className="scope-submit" type="submit" disabled={!canSubmit || busy}>
                      {flow.status === "submitting" && flow.intent === "review_requested"
                        ? "Submitting…"
                        : "Submit for Private Review"}{" "}
                      <span aria-hidden="true">↗</span>
                    </button>
                  </div>
                  {!ready && items.length > 0 && (
                    <small className="scope-download-hint">
                      Enter your name, business email, phone and company above to continue.
                    </small>
                  )}
                </form>
              )}
            </>
          )}
        </div>
        <footer>
          <button onClick={() => setOpen(false)}>Continue browsing</button>
        </footer>
      </aside>
    </>
  );
}
