"use client";
import Link from "next/link";
import {useState} from "react";
import CanadaCoverageStudy from "./canada-coverage-study/page";
import "./homepage-v3.css";

const nav=[["Services","/services"],["Business Automation","/business-automation"],["OR ONE","/or-one"],["Industries","/industries"],["Resources","/resources"],["Company","/company"]] as const;
const capabilities=[
 {code:"01",name:"Protect",title:"Cybersecurity that acts.",text:"Understand risk, strengthen protection and respond with services selected around the way your business operates.",href:"/services",link:"Explore Services"},
 {code:"02",name:"Automate",title:"Automation that scales.",text:"Remove repetitive work, connect important workflows and create more operating capacity without unnecessary complexity.",href:"/business-automation",link:"Explore Business Automation"},
 {code:"03",name:"Unify",title:"One system that brings it together.",text:"Coordinate security, automation and operational intelligence through OR ONE, built around your business.",href:"/or-one",link:"Explore OR ONE"},
] as const;
const stages=[
 {number:"01",name:"Understand",line:"See the business clearly before prescribing technology."},
 {number:"02",name:"Prioritize",line:"Focus attention and investment where they create the greatest value."},
 {number:"03",name:"Protect",line:"Apply the right security controls, services and oversight."},
 {number:"04",name:"Automate",line:"Improve defined work through practical, responsible automation."},
 {number:"05",name:"Evolve",line:"Strengthen the system as the business changes."},
] as const;
const security=["Risk","Weaknesses","Threats","People","Access","Cloud","Data","Apps","AI","Testing"] as const;
function Arrow(){return <span aria-hidden="true">↗</span>}

export default function Home(){
 const[capability,setCapability]=useState(0),[stage,setStage]=useState(0),[category,setCategory]=useState(0);
 const activeCapability=capabilities[capability],activeStage=stages[stage];
 return <main className="home-v3">
  <header className="home-nav"><Link className="home-wordmark" href="/" aria-label="ORAGROL Global home"><strong>ORAGROL</strong><small>GLOBAL</small></Link><nav aria-label="Primary navigation">{nav.map(([label,href])=><Link href={href} key={label}>{label}</Link>)}</nav><div className="home-actions"><Link className="health-link" href="/cyber-health">Get Cyber Health Score</Link><button className="home-search" aria-label="Search">⌕</button><button className="home-language" aria-label="Change language">EN <span>/ FR</span></button></div></header>
  <section className="home-hero"><div className="hero-or" aria-hidden="true">OR</div><p className="kicker">Cybersecurity first. Intelligence led.</p><h1><span>Cybersecurity that acts.</span><span>Automation that scales.</span><span>One system that brings it together.</span></h1><p className="hero-sub">Built to do the work, not simply report on it.</p><nav className="hero-choices" aria-label="ORAGROL capabilities">{capabilities.map(item=><Link href={item.href} key={item.name}><strong>{item.name==="Protect"?"Services":item.name==="Automate"?"Business Automation":"OR ONE"}</strong><span>{item.name==="Protect"?"Protect what matters.":item.name==="Automate"?"Remove what limits growth.":"Intelligence built around your business."}</span><Arrow/></Link>)}</nav></section>
  <section className="reality"><div><p className="section-label">01 / The business reality</p><h2>Growth creates capability.<br/><span>It also creates exposure.</span></h2></div><div className="reality-copy"><p>More systems, vendors, data and AI can move a business forward while making its operating environment harder to see and protect.</p><p>ORAGROL connects what is too often managed separately, giving leaders a clearer way to protect, improve and coordinate the business.</p></div><p className="reality-line">Less noise. Fewer disconnected tools. <strong>More useful action.</strong></p></section>
  <section className="capabilities"><header><p className="section-label">02 / Protect. Automate. Unify.</p><h2>Three capabilities.<br/>One business direction.</h2></header><div className="capability-stage"><nav aria-label="Select capability">{capabilities.map((item,index)=><button className={capability===index?"active":""} onMouseEnter={()=>setCapability(index)} onFocus={()=>setCapability(index)} onClick={()=>setCapability(index)} key={item.name}><span>{item.code}</span>{item.name}</button>)}</nav><article><span>{activeCapability.code}</span><p>{activeCapability.name}</p><h3>{activeCapability.title}</h3><p>{activeCapability.text}</p><Link href={activeCapability.href}>{activeCapability.link} <Arrow/></Link></article><div className="capability-or" aria-hidden="true">OR</div></div></section>
  <section className="method"><header><p className="section-label">03 / How ORAGROL works</p><h2>Clarity first.<br/>Then coordinated action.</h2><p>Move across the sequence to see how ORAGROL turns business context into practical progress.</p></header><div className="method-number" aria-hidden="true">{activeStage.number}</div><article><span>{activeStage.name}</span><h3>{activeStage.line}</h3></article><nav aria-label="ORAGROL working method">{stages.map((item,index)=><button className={stage===index?"active":""} onMouseEnter={()=>setStage(index)} onFocus={()=>setStage(index)} onClick={()=>setStage(index)} key={item.name}><span>{item.number}</span>{item.name}</button>)}</nav></section>
  <section className="security-index"><header><p className="section-label">04 / Cybersecurity</p><h2>Ten categories.<br/><span>One coordinated approach.</span></h2><p>Every service answers one question: what does this business need to protect, and what is the most direct way to protect it?</p><Link href="/services">View all cybersecurity services <Arrow/></Link></header><div className="security-orbit"><div className="orbit-ring" aria-hidden="true"/><div className="orbit-core"><strong>{String(category+1).padStart(2,"0")}</strong><span>{security[category]}</span></div>{security.map((item,index)=><button style={{"--i":index} as React.CSSProperties} className={category===index?"active":""} onMouseEnter={()=>setCategory(index)} onFocus={()=>setCategory(index)} onClick={()=>setCategory(index)} key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</button>)}</div></section>
  <section className="cyber-health-home"><div className="health-copy"><p className="section-label">05 / Start with clarity</p><h2>Know where you stand.<br/><span>Know what to do next.</span></h2><p>A guided assessment gives you a practical view of your cybersecurity position, priorities and next steps.</p><Link href="/cyber-health">Get Your Cyber Health Score <Arrow/></Link></div><div className="health-score"><span>CYBER HEALTH / ILLUSTRATIVE</span><strong>78</strong><small>/100</small><div><i style={{width:"78%"}}/><p><span>Current position</span><b>Clearer next priorities</b></p></div></div></section>
  <section className="industries-wrap"><CanadaCoverageStudy/></section>
  <section className="home-close"><p className="section-label">Clarity before complexity</p><h2>Start with a clearer view of your business.</h2><div><p>Understand your cyber health and identify what matters next.</p><Link href="/cyber-health">Get Your Cyber Health Score <Arrow/></Link><Link href="/contact">Talk to ORAGROL</Link></div></section>
  <footer className="home-footer"><div className="footer-grid"><p>Cybersecurity protection, intelligent automation and operational clarity brought together.</p><nav><strong>Explore</strong><Link href="/services">Services</Link><Link href="/business-automation">Business Automation</Link><Link href="/or-one">OR ONE</Link><Link href="/industries">Industries</Link></nav><nav><strong>Company</strong><Link href="/company">Company</Link><Link href="/resources">Resources</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></nav><div className="footer-social"><a aria-label="LinkedIn" href="https://www.linkedin.com/company/oragrol-global/" target="_blank" rel="noreferrer">in</a><a aria-label="Instagram" href="https://www.instagram.com/oragrolglobal/" target="_blank" rel="noreferrer">◎</a></div></div><div className="footer-brand">ORAGROL <small>GLOBAL</small></div><div className="footer-meta"><span>© 2026 ORAGROL GLOBAL</span><span>Thunder Bay · Ontario · Canada</span><span>EN / FR</span></div></footer>
 </main>
}
