/**
 * Cyber Health report content — the static, hand-authored library behind
 * the PDF report and lead/CRM payloads generated by
 * app/api/cyber-health/route.ts.
 *
 * Design decision (explicit, approved): this content is a FIXED library,
 * not a live LLM call. The original Tally/n8n/HubSpot pipeline appears to
 * have generated this wording with an AI step per submission — this
 * version authors one canonical, on-brand entry per question instead.
 * Reasons: no new API key/cost per report, no latency, no risk of an AI
 * inventing an inaccurate security claim under the ORAGROL brand, and the
 * output is fully predictable/reviewable ahead of time — the standard a
 * real MSSP report is held to. The "AI-Assisted Assessment" framing still
 * holds honestly: the assessment adapts in real time to the person's
 * actual answers (filtering, weighting, category grouping, roadmap
 * sequencing), it just doesn't generate prose live.
 */
import { categories, questions } from "./assessment-data";

export type Severity = "Critical" | "High" | "Medium" | "Low";
export type Answer = "Yes" | "No" | "Not Sure";

export interface Finding {
  id: string; // question id, e.g. "Q05-1"
  title: string;
  severity: Severity;
  businessImpact: string;
  likelihood: string;
  action: string;
  effort: "Low" | "Medium" | "High";
  timeRequired: string;
}

// One entry per question. Applies whenever the answer is not "Yes"
// ("No" and "Not Sure" share a finding — see the file header for why).
export const FINDINGS: Record<string, Omit<Finding, "id">> = {
  "Q01-1": {
    title: "Password reuse across work accounts",
    severity: "Medium",
    businessImpact: "Moderate — a single compromised password can expose multiple systems.",
    likelihood: "Likely",
    action: "Roll out a password manager business-wide and require a unique password for every work account.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q01-2": {
    title: "Default passwords left unchanged on new devices",
    severity: "Medium",
    businessImpact: "Moderate — default credentials are the first thing attackers try.",
    likelihood: "Possible",
    action: "Add default-password changes to your standard device and software setup checklist.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q02-1": {
    title: "Multi-factor authentication not enforced on core accounts",
    severity: "Critical",
    businessImpact: "Severe — MFA gaps are one of the most common ways businesses get breached.",
    likelihood: "Likely",
    action: "Enable MFA on email and every business-critical account immediately, starting with admin accounts.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q02-2": {
    title: "No MFA required for remote access",
    severity: "High",
    businessImpact: "Severe — remote sign-ins without MFA are a leading entry point for attackers.",
    likelihood: "Likely",
    action: "Require MFA for any sign-in from outside the office, with no exceptions.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q03-1": {
    title: "Inadequate email filtering",
    severity: "High",
    businessImpact: "Severe — most breaches start with a phishing email that reaches an inbox.",
    likelihood: "Likely",
    action: "Deploy a proper email security filter (e.g. Microsoft Defender for Office 365 or an equivalent) ahead of employee inboxes.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q03-2": {
    title: "No phishing awareness training in the past year",
    severity: "Medium",
    businessImpact: "Moderate — untrained staff are far more likely to click a malicious link.",
    likelihood: "Likely",
    action: "Run a short phishing-awareness session for all staff and repeat it at least annually.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q03-3": {
    title: "No simple way to report suspicious emails",
    severity: "Medium",
    businessImpact: "Moderate — threats go unreported and unaddressed until it's too late.",
    likelihood: "Possible",
    action: "Set up a one-click \"report phishing\" option or a dedicated inbox employees can use immediately.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q04-1": {
    title: "Missing or inconsistent antivirus/anti-malware coverage",
    severity: "High",
    businessImpact: "Severe — unprotected endpoints are an easy target for malware and ransomware.",
    likelihood: "Likely",
    action: "Deploy managed antivirus/EDR across every company device and confirm it's actively running.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q04-2": {
    title: "Devices not set to auto-lock",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption, but easy to fix.",
    likelihood: "Unlikely",
    action: "Enforce a short auto-lock timeout on every company laptop and desktop.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q05-1": {
    title: "Lack of automatic software updates",
    severity: "Medium",
    businessImpact: "Moderate — manageable but should not be ignored.",
    likelihood: "Possible",
    action: "Immediately implement automatic software updates to ensure timely security patches.",
    effort: "Medium",
    timeRequired: "1-2 weeks",
  },
  "Q05-2": {
    title: "Unverified support for current software and hardware",
    severity: "Medium",
    businessImpact: "Moderate — manageable but should not be ignored.",
    likelihood: "Possible",
    action: "Verify that all software and hardware in use are still supported with security updates to mitigate vulnerabilities.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q06-1": {
    title: "Backups not running on a regular automated schedule",
    severity: "Critical",
    businessImpact: "Severe — without reliable backups, an incident can mean permanent data loss.",
    likelihood: "Possible",
    action: "Set up automated daily (or more frequent) backups for all critical business data.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q06-2": {
    title: "Backup restore never actually tested",
    severity: "High",
    businessImpact: "Severe — an untested backup is not a guaranteed recovery.",
    likelihood: "Possible",
    action: "Run a real backup-restore test at least twice a year, not just confirm the backup ran.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q06-3": {
    title: "Low confidence in ransomware recovery",
    severity: "High",
    businessImpact: "Severe — inability to recover without paying puts the business at the attacker's mercy.",
    likelihood: "Possible",
    action: "Build and document a ransomware recovery plan, and confirm backups are isolated from the main network.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q07-1": {
    title: "Guest and office Wi-Fi not properly separated",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Password-protect office Wi-Fi and put guest devices on a separate network.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q07-2": {
    title: "No firewall protecting the business network",
    severity: "Medium",
    businessImpact: "Moderate — an unprotected network is easier to probe and exploit.",
    likelihood: "Possible",
    action: "Deploy a business-grade firewall between your network and the internet.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q08-1": {
    title: "Cloud platform security features not fully enabled",
    severity: "High",
    businessImpact: "Severe — sign-in alerts and multi-factor sign-in are core defenses against account takeover.",
    likelihood: "Possible",
    action: "Turn on all available sign-in protection and suspicious-activity alerts in your cloud admin settings.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q08-2": {
    title: "Shared file and folder access not periodically reviewed",
    severity: "Medium",
    businessImpact: "Moderate — stale access grows quietly and widens exposure over time.",
    likelihood: "Possible",
    action: "Schedule a recurring review of who has access to shared drives and folders.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q08-1-GWS": {
    title: "Google Workspace security features not fully enabled",
    severity: "High",
    businessImpact: "Severe — 2-Step Verification and sign-in alerts are core defenses against account takeover.",
    likelihood: "Possible",
    action: "Turn on 2-Step Verification and suspicious sign-in alerts in your Google Workspace admin settings.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q08-2-GWS": {
    title: "Shared Google Drive access not periodically reviewed",
    severity: "Medium",
    businessImpact: "Moderate — stale access grows quietly and widens exposure over time.",
    likelihood: "Possible",
    action: "Schedule a recurring review of who has access to shared Google Drive files and folders.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q09-1": {
    title: "No cybersecurity awareness training provided",
    severity: "Medium",
    businessImpact: "Moderate — employees are the first line of defense and need basic training.",
    likelihood: "Likely",
    action: "Introduce a short, recurring security-awareness training program for all staff.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q09-2": {
    title: "No written technology-use policy",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Create a simple, one-page acceptable-use policy employees can reference.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q10-1": {
    title: "Employees have broader access than their role requires",
    severity: "High",
    businessImpact: "Severe — excess access multiplies the damage from any single compromised account.",
    likelihood: "Possible",
    action: "Review permissions and restrict access to only what each role actually needs.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q10-2": {
    title: "Access not promptly removed when employees leave",
    severity: "High",
    businessImpact: "Severe — former employees retaining access is a direct, avoidable breach path.",
    likelihood: "Possible",
    action: "Build access removal into your standard offboarding checklist, effective on the employee's last day.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q11-1": {
    title: "Company mobile devices not protected with a passcode or biometric lock",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Require a passcode or biometric lock on every company-owned phone and tablet.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q11-2": {
    title: "No ability to remotely lock or wipe a lost device",
    severity: "Medium",
    businessImpact: "Moderate — a lost or stolen device without remote wipe is an open door to company data.",
    likelihood: "Unlikely",
    action: "Enable mobile device management (MDM) so lost or stolen devices can be locked or wiped remotely.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q12-1": {
    title: "Insecure remote connections for employees",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Establish a secure VPN connection for remote employees to protect data during transmission.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q12-2": {
    title: "No security standards for personal devices accessing company data",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Create and enforce security standards for personal devices accessing company data, including passcodes and updated software.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q13-1": {
    title: "Sensitive data stored outside approved systems",
    severity: "Medium",
    businessImpact: "Moderate — personal email and personal cloud drives fall outside company control.",
    likelihood: "Possible",
    action: "Require sensitive business and customer data to be stored only in approved company systems.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q13-2": {
    title: "Sensitive data not encrypted",
    severity: "Medium",
    businessImpact: "Moderate — unencrypted data is fully exposed if intercepted or accessed improperly.",
    likelihood: "Possible",
    action: "Enable encryption for sensitive data at rest and in transit wherever it's stored or sent.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q14-1": {
    title: "Unclear which vendors have access to systems or data",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Build and maintain a simple list of every vendor with access to your systems or data.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q14-2": {
    title: "Vendor security practices not reviewed",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Ask key vendors what security practices they follow to protect any data they share.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q15-1": {
    title: "Website not confirmed to use HTTPS",
    severity: "Medium",
    businessImpact: "Moderate — a missing padlock damages trust and can expose visitor data.",
    likelihood: "Unlikely",
    action: "Confirm your website and any customer login area use HTTPS everywhere.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q15-2": {
    title: "Website and login areas not kept updated or monitored",
    severity: "Medium",
    businessImpact: "Moderate — an outdated public-facing site is a common entry point.",
    likelihood: "Possible",
    action: "Keep website software updated and put basic uptime/security monitoring in place.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q16-1": {
    title: "Card details may be stored outside a PCI-compliant processor",
    severity: "High",
    businessImpact: "Severe — storing card data yourself carries serious compliance and breach risk.",
    likelihood: "Unlikely",
    action: "Route all card payments through a PCI-compliant payment processor rather than storing card details directly.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q16-2": {
    title: "Banking and financial system access not tightly limited",
    severity: "Medium",
    businessImpact: "Moderate — broad access to financial systems increases fraud exposure.",
    likelihood: "Possible",
    action: "Limit online banking and financial system access to a small number of trusted people.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q17-1": {
    title: "No plan for a suspected cyberattack or data breach",
    severity: "High",
    businessImpact: "Severe — the first hours after an incident are the most damaging without a plan.",
    likelihood: "Possible",
    action: "Put a simple, written incident response plan in place and share it with the team.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q17-2": {
    title: "Employees unclear who to contact about a suspicious event",
    severity: "Medium",
    businessImpact: "Moderate — delays in reporting let small issues become bigger ones.",
    likelihood: "Possible",
    action: "Make sure every employee knows exactly who to contact the moment something looks suspicious.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q18-1": {
    title: "Unrestricted access to sensitive information",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Restrict access to servers and sensitive paperwork to authorized personnel only to prevent unauthorized access.",
    effort: "Low",
    timeRequired: "1-2 weeks",
  },
  "Q18-2": {
    title: "Screens not locked when employees step away",
    severity: "Medium",
    businessImpact: "Moderate — manageable but should not be ignored.",
    likelihood: "Possible",
    action: "Ensure that computer screens are locked or logged off when employees step away to protect sensitive information from prying eyes.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q19-1": {
    title: "No one assigned responsibility for cybersecurity decisions",
    severity: "Medium",
    businessImpact: "Moderate — manageable but should not be ignored.",
    likelihood: "Possible",
    action: "Assign a specific person or role responsible for cybersecurity decisions to enhance accountability and oversight.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q19-2": {
    title: "Cybersecurity spending not reviewed annually",
    severity: "Medium",
    businessImpact: "Moderate — manageable but should not be ignored.",
    likelihood: "Possible",
    action: "Review cybersecurity spending and investments at least once a year to ensure adequate funding and resource allocation.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q20-1": {
    title: "No cyber liability insurance in place",
    severity: "Medium",
    businessImpact: "Moderate — a single incident can create costs no policy is covering.",
    likelihood: "Possible",
    action: "Evaluate a cyber liability insurance policy sized to your business's risk exposure.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
  "Q20-2": {
    title: "Unclear which regulatory requirements apply",
    severity: "Low",
    businessImpact: "Limited — low immediate business disruption.",
    likelihood: "Unlikely",
    action: "Confirm which requirements (e.g. PIPEDA, PCI-DSS) apply to your business and document how you meet them.",
    effort: "Medium",
    timeRequired: "2-4 weeks",
  },
};

// Sanity check at module load, dev-time only: every question in
// assessment-data.ts must have a matching finding entry.
if (process.env.NODE_ENV !== "production") {
  const missing = questions.map((q) => q.id).filter((id) => !FINDINGS[id]);
  if (missing.length) {
    console.warn(`[cyber-health/report-data] Missing FINDINGS entries for: ${missing.join(", ")}`);
  }
}

// The 5 executive-report groupings, mapped onto the 20 existing scoring
// categories (ids from assessment-data.ts).
export const CATEGORY_GROUPS: { name: string; categoryIds: string[] }[] = [
  { name: "Identity Security", categoryIds: ["01", "02", "10"] },
  { name: "Infrastructure", categoryIds: ["03", "04", "05", "07", "11", "12", "15"] },
  { name: "Cloud & Data", categoryIds: ["06", "08", "13", "16"] },
  { name: "Governance", categoryIds: ["09", "14", "19"] },
  { name: "Business Resilience", categoryIds: ["17", "18", "20"] },
];

export function categoryIdsForGroup(name: string): string[] {
  return CATEGORY_GROUPS.find((g) => g.name === name)?.categoryIds ?? [];
}

// A curated 5-item "at a glance" strip — one representative category per
// pillar, not the same list as CATEGORY_GROUPS above.
export const SNAPSHOT_CATEGORIES: { label: string; categoryIds: string[] }[] = [
  { label: "Identity", categoryIds: ["01", "02"] },
  { label: "Email", categoryIds: ["03"] },
  { label: "Backup", categoryIds: ["06"] },
  { label: "Cloud", categoryIds: ["08"] },
  { label: "Governance", categoryIds: ["19"] },
];

export function groupDescription(pct: number): string {
  if (pct >= 90) return "a genuine strength — a solid foundation the rest of the business can rely on.";
  if (pct >= 60) return "broadly sound, with a few specific gaps worth closing.";
  if (pct >= 40) return "showing real gaps that should be prioritized soon.";
  return "a significant risk area that needs attention first.";
}

export function maturityLabel(score: number): string {
  if (score >= 80) return "Strong";
  if (score >= 60) return "Needs Improvement";
  if (score >= 40) return "At Risk";
  return "Critical";
}

export function riskTier(score: number): "Low" | "Medium" | "High" | "Critical" {
  return score >= 80 ? "Low" : score >= 60 ? "Medium" : score >= 40 ? "High" : "Critical";
}

export type PackageTier = "Starter" | "Standard" | "Premium";

export function recommendedPackage(score: number): PackageTier {
  return score >= 80 ? "Starter" : score >= 60 ? "Standard" : "Premium";
}

export const PACKAGE_CONTENT: Record<
  PackageTier,
  { timeline: string; why: string; included: string[]; outcome: string; idealFor: string }
> = {
  Starter: {
    timeline: "30-60 Days",
    why: "Your foundation is solid — the Starter package closes the remaining gaps without over-building.",
    included: [
      "A tailored remediation plan for the specific gaps found",
      "Guided setup for the highest-priority items",
      "A follow-up check-in once changes are in place",
    ],
    outcome: "A confirmed, fully closed baseline with no material gaps left open.",
    idealFor: "Businesses at your current risk tier and maturity level.",
  },
  Standard: {
    timeline: "60-90 Days",
    why: "Based on your assessment results, the Standard package is the recommended starting point for your current risk profile.",
    included: [
      "A tailored remediation plan",
      "Ongoing monitoring and support",
      "Regular check-ins with your advisor",
    ],
    outcome: "A measurable reduction in risk exposure and a clearer path toward stronger cyber resilience.",
    idealFor: "Businesses at your current risk tier and maturity level.",
  },
  Premium: {
    timeline: "90-120 Days",
    why: "Several core areas need attention at once — the Premium package addresses them together rather than one at a time.",
    included: [
      "A full remediation roadmap across every flagged category",
      "Active monitoring and incident response coverage",
      "A dedicated advisor with regular strategic reviews",
    ],
    outcome: "A structured path from your current risk tier to a defensible, audited baseline.",
    idealFor: "Businesses at your current risk tier and maturity level.",
  },
};

export function generateClientReference(): string {
  const year = new Date().getFullYear();
  const n = Math.floor(100000 + Math.random() * 900000);
  return `OCR-${year}-${n}`;
}

export function generateReportId(): string {
  const year = new Date().getFullYear();
  const n = Math.floor(100000 + Math.random() * 900000);
  return `ORG-${year}-${n}`;
}

export { categories };
